spring:
  datasource:
    driverClassName: "org.postgresql.Driver"
    url:  ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    jpa:
      generate-ddl: true
      hibernate.ddl-auto: create
      show-sql: true